# Generated by Django 2.1.1 on 2018-09-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('application_form_link', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('application_start_date', models.DateTimeField()),
                ('application_end_date', models.DateTimeField()),
                ('event_date', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_photo/')),
            ],
        ),
    ]
